### ISSUE TITLE
Need Detailed Guidelines for Creating Storybook Examples and JSON Files

### ISSUE THREAD

**Issue by anonymousRecords** [meursyphus/react-notion-custom#12]
While contributing to the react-notion-custom project, I felt the need for more detailed guidelines on creating Storybook examples and JSON files. The current guide only explains the basic structure, and I believe additional information on the following points would be beneficial:

1. Storybook examples:
   - What types of examples should be created for each component (basic, variations, edge cases, etc.)
   - The scope and depth of example data (minimal data vs. various scenarios)
   - When and how to add interactive controls

2. JSON files:
   - Required data structures and fields
   - Consistency with actual Notion API responses
   - Methods for generating test data (manual vs. automated tools)

Having such guidelines would enable contributors to create consistent, high-quality examples and test data, which would ultimately improve the overall quality of the project.

**Comment by Moon-DaeSeung** [comment]
it start with minimal data. but It will be updated as the library grow

we will support ui test with chromatic and interaction test with storybook plugin. 

we also test it in dark-mode. however this library is just beginning. so I think it's okay with small senario
