### ISSUE TITLE
[Notion Block] Support `Table` block type

### ISSUE THREAD

**Issue by Moon-DaeSeung** [meursyphus/react-notion-custom#34]
Support `Table` notion block.

Here is reference: https://github.com/meursyphus/react-notion-custom/pull/9#pullrequestreview-2320838474

you should check guideline on https://github.com/meursyphus/react-notion-custom/blob/main/packages/react-notion-custom/CONTRIBUTING.md

ps. Table in svelte-notion-page is shit. you'd better design it by your self

**Comment by myjeong19** [comment]
I am currently working on supporting this block. @myjeong19

**Comment by myjeong19** [comment]
The issue has been completed. #79
