### ISSUE TITLE
Bug The caption of the image block in Notion is not being retrieved

### ISSUE THREAD

**Issue by myjeong19** [meursyphus/react-notion-custom#52]
#51 Upon checking the [image.json](https://github.com/meursyphus/react-notion-custom/pull/51/commits/8c12664776e27c2ee511d04399ab021121137330#diff-6d89e22b669ff472f40744b2e30e1a6ccfe528681fe955af717718a6319a0ef0), I can confirm that the Notion caption is an empty array.

![스크린샷 2024-10-02 오전 2 09 41](https://github.com/user-attachments/assets/032bc13b-081c-4fa3-99d3-788f4ae7073b)

**Comment by Moon-DaeSeung** [comment]
that is resolved
